# Generated by Django 5.0.6 on 2024-07-04 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table='evento',
        ),
    ]
